version: "3.7"

services: 

  nginx:
    image: nginx-custom-dockerfile
    build:
      dockerfile: nginx-custom-dockerfile
    ports:
      - "80:80"
    restart: always
    hostname: nginx
    command: [nginx,"-g","daemon off;"]

  flask-app:
    image: web-dockerfile
    hostname: flask-app
    build: 
      dockerfile: web-dockerfile
    restart: always
